---
env:
    browser: true
    es2021: true
extends:
    # - eslint:recommended
    - standard
    - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: tsconfig.json
plugins:
    - '@typescript-eslint'
ignorePatterns:
    - dist/
    - node_modules/
    - src/logger/pino-loki
rules: {
    max-len: [off, 120],
    indent: [error, 4],
    require-jsdoc: 0,

    multiline-ternary: off,
    no-throw-literal: off,
    operator-linebreak: off,
    comma-dangle: off,
    curly: off,
    eqeqeq: off,
    no-unused-vars: off,
    '@typescript-eslint/no-unused-vars': ['error', {argsIgnorePattern: '^_', varsIgnorePattern: '^_'}],
    '@typescript-eslint/switch-exhaustiveness-check': 'warn',
    '@typescript-eslint/no-non-null-assertion': off,
    '@typescript-eslint/no-var-requires': off,
}
